language: node_js
node_js:
  - "7"
script: "npm run-script test-travis"
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage -t $CODACY_PROJECT_TOKEN
addons:
  srcclr: true